# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clonacion de codigo
        uses: actions/checkout@v4
     
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'
      
      - name: Compilacion maven
        run: |
          mvn package

      - name: Ejecucion Test Unitarios
        run: |
          mvn test verify
     
      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Analisis SonarCloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=rvalenzuelamu \
          -Dsonar.projectKey=rvalenzuelamu_microservicio-java
          -Dsonar.coverage.jacoco.xmlReportPaths=../testing-web-complete/target/site/jacoco/jacoco.xml

      - name: SonarQube Quality Gate check
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        with:
          scanMetadataReportFile: target/sonar/report-task.txt

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: 987219263
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Docker build
        run: | 
          docker build -t 987219263/microservicio-java:latest .

      - name: Docker push
        run: | 
          docker push 987219263/microservicio-java:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:

      - name: Clonacion de codigo
        uses: actions/checkout@v4
      
      - name: Despliegue
        run: |
          kubectl apply -f deploy.yaml
